/**
 * Writer language menu — 100+ languages across every region.
 *
 * A static list is deliberate: the whole table is a few kilobytes, needs no
 * fetch, no storage and no memory to speak of. `id` is what the model is
 * asked to write in; `label` is the endonym shown in the menu.
 * 'auto' (mirror the idea's language) is handled by the UI, not this list.
 */
export interface WriterLanguage {
  id: string;
  label: string;
}

export const WRITER_LANGUAGES: WriterLanguage[] = [
  { id: 'English', label: 'English' },
  { id: 'Bahasa Melayu', label: 'Melayu' },
  { id: '中文', label: '中文' },
  { id: 'Tamil', label: 'Tamil' },
  { id: 'Afrikaans', label: 'Afrikaans' },
  { id: 'Albanian', label: 'Shqip' },
  { id: 'Amharic', label: 'አማርኛ' },
  { id: 'Arabic', label: 'العربية' },
  { id: 'Armenian', label: 'Հայերեն' },
  { id: 'Azerbaijani', label: 'Azərbaycanca' },
  { id: 'Basque', label: 'Euskara' },
  { id: 'Belarusian', label: 'Беларуская' },
  { id: 'Bengali', label: 'বাংলা' },
  { id: 'Bosnian', label: 'Bosanski' },
  { id: 'Bulgarian', label: 'Български' },
  { id: 'Burmese', label: 'မြန်မာ' },
  { id: 'Cantonese', label: 'Cantonese' },
  { id: 'Catalan', label: 'Català' },
  { id: 'Cebuano', label: 'Cebuano' },
  { id: 'Czech', label: 'Čeština' },
  { id: 'Danish', label: 'Dansk' },
  { id: 'Dutch', label: 'Nederlands' },
  { id: 'Esperanto', label: 'Esperanto' },
  { id: 'Estonian', label: 'Eesti' },
  { id: 'Filipino', label: 'Filipino' },
  { id: 'Finnish', label: 'Suomi' },
  { id: 'French', label: 'Français' },
  { id: 'Galician', label: 'Galego' },
  { id: 'Georgian', label: 'ქართული' },
  { id: 'German', label: 'Deutsch' },
  { id: 'Greek', label: 'Ελληνικά' },
  { id: 'Gujarati', label: 'ગુજરાતી' },
  { id: 'Haitian Creole', label: 'Kreyòl' },
  { id: 'Hausa', label: 'Hausa' },
  { id: 'Hebrew', label: 'עברית' },
  { id: 'Hindi', label: 'हिन्दी' },
  { id: 'Hungarian', label: 'Magyar' },
  { id: 'Icelandic', label: 'Íslenska' },
  { id: 'Igbo', label: 'Igbo' },
  { id: 'Indonesian', label: 'Bahasa Indonesia' },
  { id: 'Irish', label: 'Gaeilge' },
  { id: 'Italian', label: 'Italiano' },
  { id: 'Japanese', label: '日本語' },
  { id: 'Javanese', label: 'Basa Jawa' },
  { id: 'Kannada', label: 'ಕನ್ನಡ' },
  { id: 'Kazakh', label: 'Қазақша' },
  { id: 'Khmer', label: 'ខ្មែរ' },
  { id: 'Korean', label: '한국어' },
  { id: 'Kurdish', label: 'Kurdî' },
  { id: 'Kyrgyz', label: 'Кыргызча' },
  { id: 'Lao', label: 'ລາວ' },
  { id: 'Latin', label: 'Latin' },
  { id: 'Latvian', label: 'Latviešu' },
  { id: 'Lithuanian', label: 'Lietuvių' },
  { id: 'Macedonian', label: 'Македонски' },
  { id: 'Malagasy', label: 'Malagasy' },
  { id: 'Malayalam', label: 'മലയാളം' },
  { id: 'Maltese', label: 'Malti' },
  { id: 'Maori', label: 'Te Reo Māori' },
  { id: 'Marathi', label: 'मराठी' },
  { id: 'Mongolian', label: 'Монгол' },
  { id: 'Nepali', label: 'नेपाली' },
  { id: 'Norwegian', label: 'Norsk' },
  { id: 'Pashto', label: 'پښتو' },
  { id: 'Persian', label: 'فارسی' },
  { id: 'Polish', label: 'Polski' },
  { id: 'Portuguese', label: 'Português' },
  { id: 'Punjabi', label: 'ਪੰਜਾਬੀ' },
  { id: 'Quechua', label: 'Quechua' },
  { id: 'Romanian', label: 'Română' },
  { id: 'Russian', label: 'Русский' },
  { id: 'Samoan', label: 'Gagana Samoa' },
  { id: 'Serbian', label: 'Српски' },
  { id: 'Shona', label: 'chiShona' },
  { id: 'Sinhala', label: 'සිංහල' },
  { id: 'Slovak', label: 'Slovenčina' },
  { id: 'Slovenian', label: 'Slovenščina' },
  { id: 'Somali', label: 'Soomaali' },
  { id: 'Spanish', label: 'Español' },
  { id: 'Sundanese', label: 'Basa Sunda' },
  { id: 'Swahili', label: 'Kiswahili' },
  { id: 'Swedish', label: 'Svenska' },
  { id: 'Tajik', label: 'Тоҷикӣ' },
  { id: 'Telugu', label: 'తెలుగు' },
  { id: 'Thai', label: 'ไทย' },
  { id: 'Tibetan', label: 'བོད་སྐད་' },
  { id: 'Turkish', label: 'Türkçe' },
  { id: 'Turkmen', label: 'Türkmençe' },
  { id: 'Ukrainian', label: 'Українська' },
  { id: 'Urdu', label: 'اردو' },
  { id: 'Uyghur', label: 'ئۇيغۇرچە' },
  { id: 'Uzbek', label: "Oʻzbek" },
  { id: 'Vietnamese', label: 'Tiếng Việt' },
  { id: 'Welsh', label: 'Cymraeg' },
  { id: 'Xhosa', label: 'isiXhosa' },
  { id: 'Yiddish', label: 'ייִדיש' },
  { id: 'Yoruba', label: 'Yorùbá' },
  { id: 'Zulu', label: 'isiZulu' },
];
